[INFO][0][<module>] Linux dec0008 5.14.21-150400.24.46_12.0.73-cray_shasta_c #1 SMP Thu May 18 23:03:34 UTC 2023 (9c4698c) x86_64 x86_64
[INFO][0][<module>] /glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB (2.7)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl-2023a/lib/python3.9/site-packages/numpy (1.23.5)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl-2023a/lib/python3.9/site-packages/matplotlib (3.6.3)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl-2023a/lib/python3.9/site-packages/netCDF4 (1.6.2)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl-2023a/lib/python3.9/site-packages/cf_units (3.1.1)
[INFO][0][<module>] /glade/u/home/rfisher/.local/lib/python3.9/site-packages/sympy (1.12)
[INFO][0][<module>] /glade/u/apps/opt/conda/envs/npl-2023a/lib/python3.9/site-packages/mpi4py (3.1.4)
[INFO][0][<module>] 2023-09-07 02:29:25.347452
[INFO][0][MakeComparable][Biomass/GlobalCarbon][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [  1 360 720] after: [  1 360 711]
[INFO][0][AnalysisMeanStateSpace][biomass] Bias scored using Collier2018
[INFO][0][confront][Biomass/GlobalCarbon][RTM_ens37_case_1] Success
[INFO][0][MakeComparable][Biomass/GlobalCarbon][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [  1 360 720] after: [  1 360 711]
[DEBUG][0][WorkConfront][Biomass/GlobalCarbon][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/EcosystemandCarbonCycle/Biomass/GlobalCarbon/GlobalCarbon_RTM_ens37_case_2.nc'

[INFO][0][MakeComparable][Biomass/NBCD2000][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [  1 360 720] after: [  1 360 711]
[DEBUG][0][WorkConfront][Biomass/NBCD2000][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
P[INFO][0][AnalysisMeanStateSpace][biomass] Bias scored using Collier2018
[INFO][0][confront][Biomass/NBCD2000][RTM_ens37_case_0] [INFO][0[INFO][0][MakeComparable][Biomass/NBCD2000][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [  1 360 720] after: [  1 3[DEBUG][0][WorkConfront][Biomass/NBCD2000][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
P[DEBUG][0][WorkConfront][Biomass/NBCD2000][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2[INFO][0[INFO][0][MakeComparable][Biomass/NBCD2000][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [  1 360 720] after: [  1 3[DEBUG][[DEBUG][0][WorkConfront][Biomass/NBCD2000][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_s[DEBUG][0][WorkConfront][Biomass/NBCD2000][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2[INFO][0][MakeComparable][Biomass/USForest][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [  1 360 720] after: [  1 360 711]
[DEBUG][0][WorkConfront][Biomass/USForest][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
P[DEBUG][0][WorkConfront][Biomass/USForest][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2[INFO][0][MakeComparable][Biomass/USForest][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [  1 360 720] after: [  1 360 711]
[DEBUG][[DEBUG][0][WorkConfront][Biomass/USForest][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_s[DEBUG][0][WorkConfront][Biomass/USForest][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2[INFO][0][MakeComparable][Biomass/USForest][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [  1 360 720] after: [  1 360 711]
[DEBUG][0][WorkConfront][Biomass/USForest][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/EcosystemandCarbonCycle/Biomass/USForest/USForest_RTM_ens37_case_2.nc'

[INFO][0[INFO][0][MakeComparable][Biomass/Thurner][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [  1 360 720] after: [  1 3[DEBUG][[DEBUG][0][WorkConfront][Biomass/Thurner][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_su[INFO][0][AnalysisMeanStateSpace][biomass] Bias scored using Collier2018
[INFO][0][confront][Biomass/Thurner][RTM_ens37_case_0[INFO][0[INFO][0][MakeComparable][Biomass/Thurner][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [  1 360 720] after: [  1 3[DEBUG][0][WorkConfront][Biomass/Thurner][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
Pe[INFO][0][AnalysisMeanStateSpace][biomass] Bias scored using Collier2018
[INFO][0][confront][Biomass/Thurner][RTM_ens37_case_1[INFO][0][[INFO][0][MakeComparable][Biomass/Thurner][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [  1 360 720] after: [  1[DEBUG][[D[DEBUG][0][WorkConfront][Biomass/Thurner][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_[DEBUG][0][WorkConfront][Biomass/Thurner][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0[INFO][0][[INFO][0][MakeComparable][Biomass/ESACCI][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [  1 281 721] after: [  1 281 711]
[INFO][0][MakeComparable][Biomass/ESACCI][RTM_ens37_case_0] Spatial data was clipped from the comparison:  before: [12 46 72] after: [[DEBUG][0][WorkConfront][Biomass/ESACCI][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
Per[INFO][0][AnalysisMeanStateSpace][biomass] Bias scored using Collier2018
[INFO][0][confront][Biomass/ESACCI][RTM_ens37_case[INFO][0[I[INFO][0][MakeComparable][Biomass/ESACCI][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [  1 281 721] after: [  1 281 711[I[INFO][0][MakeComparable][Biomass/ESACCI][RTM_ens37_case_1] Spatial data was clipped from the comparison:  before: [12 46 72] after: [[DEBUG][[D[DEBUG][0][WorkConfront][Biomass/ESACCI][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_s[INFO][0][AnalysisMeanStateSpace][biomass] Bias scored using Collier2018
[INFO][0][confront][Biomass/ESACCI][RTM_ens37_case[INFO][0][[INFO][0][MakeComparable][Biomass/ESACCI][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [  1 281 721] after: [  1[INFO][0][[INFO][0][MakeComparable][Biomass/ESACCI][RTM_ens37_case_2] Spatial data was clipped from the comparison:  before: [12 46 72] after: [[DEBUG][0][D[INFO][0][AnalysisMeanStateSpace][biomass] Bias scored using Collier2018
[INFO][0][confront][Biomass/ESACCI][RTM_ens37_case_2] Success
[DEBUG][0][WorkConfront][GrossPrimaryProductivity/FLUXNET2015][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in net[DEBUG][0][WorkConfront][GrossPrimaryProductivity/FLUXNET2015][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilam[DEBUG][0][WorkConfront][GrossPrimaryProductivity/FLUXNET2015][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 20[DEBUG][0][WorkConfront][GrossPrimaryProductivity/[DEBUG][0][WorkConfront][GrossPrimaryProductivity/FLUXNET2015][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c[DEBUG][0][WorkConfront][GrossPrimaryProductivity/FLUXNET2015][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 20[DEBUG][0][WorkConfront][GrossPrimaryProductivity/FLUXNET2015][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c[INFO][0][confront][GrossPrimaryProductivity/FLUXN[INFO][0][MakeComparable][GrossPri[INFO][0][MakeComparable][GrossPrimaryProductivity/FLUXCOM][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [[DEBUG][0][WorkConfront][GrossPrim[DEBUG][0][WorkConfront][GrossPrimaryProductivity/FLUXCOM][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_n[DEBUG][0][WorkConfront][GrossPrimaryProductivity/FLUXCOM][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/fi[INFO][0][MakeComparable][GrossPrimaryProductivity/FLUXCOM][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [408 360 720] after: [408 360 711]
[DEBUG][0][WorkConfront][GrossPrimaryProductivity/FLUXCOM][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/EcosystemandCarbonCycle/GrossPrimaryProductivity/FLUXCOM/FLUXCOM_RTM_ens37_case_1.nc'

[INFO][0][MakeComparable][GrossPrimaryProductivity/FLUXCOM][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [408 360 720] after: [408 360 711]
[DEBUG][0][WorkConfront][GrossPrimaryProductivity/FLUXCOM][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, [DEBUG][0][DEBUG][0][WorkConfront][GrossPrimaryProductivity/FLUXCOM][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/fi[INFO][0][MakeComparable][GrossPrimaryProductivity/WECANN][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [108 180 360] after: [108 180 356]
[DEBUG][0][WorkConfront][GrossPrim[DEBUG][0][WorkConfront][GrossPrimaryProductivity/WECANN][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_ne[DEBUG][0][WorkConfront][GrossPrimaryProductivity/WECANN][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/[INFO][0][MakeComparable][GrossPrimaryProductivity/WECANN][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [108 180 360] after: [108 180 356]
[DEBUG][0][WorkConfront][GrossPrim[DEBUG][0][WorkConfront][GrossPrimaryProductivity/WECANN][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/n[DEBUG][0][WorkConfront][GrossPrimaryProductivity/WECANN][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilam[INFO][0][MakeComparable][GrossPri[INFO][0][MakeComparable][GrossPrimaryProductivity/WECANN][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [[DEBUG][0][WorkConfront][GrossPrim[DEBUG][0][WorkConfront][GrossPrimaryProductivity/WECANN][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/n[DEBUG][0][WorkConfront][GrossPrimaryProductivity/[DEBUG][0][WorkConfront][GrossPrimaryProductivity/WECANN][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/pal[INFO][0][MakeComparable][LeafArea[INFO][0][MakeComparable][LeafAreaIndex/AVHRR][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [[DEBUG][0][WorkConfront][LeafAreaIndex/AVHRR][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._n[DEBUG][0][DEBUG][0][WorkConfront][LeafAreaIndex/A[DEBUG][0][WorkConfront][LeafAreaIndex/AVHRR][RTM_ens37_case_0]
Traceback (most recent call last):
  File [INFO][0][MakeComparable][LeafAreaIndex/AVHRR][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [348 360 720] after: [348 360 711]
[DEBUG][0][WorkConfront][LeafAreaIndex/AVHRR][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._n[DEBUG][0][WorkConfront][LeafAreaIndex/AVHRR][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d8737[INFO][0][MakeComparable][LeafAreaIndex/AVHRR][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [348 360 720] after: [348 360 711]
[DEBUG][0][WorkConfront][LeafAreaI[DEBUG][0][WorkConfront][LeafAreaIndex/AVHRR][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF[INFO][0][MakeComparable][LeafAreaIndex/AVHRR][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [348 360 720] after: [348 360 711]
[DEBUG][0][WorkConfront][LeafAreaIndex/AVHRR][RTM_ens37_case_2]
Traceback (most rec[INFO][0][MakeComparable][LeafAreaIndex/AVH15C1][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [468 360 720] after: [468 360 711]
[DEBUG][0][WorkConfront][LeafAreaIndex/AVH15C1][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4.[DEBUG][0][D[DEBUG][0][WorkConfront][LeafAreaIndex/AVH15C1][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1[INFO][0][MakeComparable][LeafArea[INFO][0][MakeComparable][LeafAreaIndex/AVH15C1][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [[DEBUG][0][WorkConfront][LeafAreaIndex/AVH15C1][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._[DEBUG][0][WorkConfront][LeafAreaIndex/AVH15C1][RTM_ens37_case_[INFO][0][AnalysisMeanStateSpace][lai] Bias scored using Collier2018
[INFO][0][AnalysisMe[INFO][0][MakeComparable][LeafArea[INFO][0][MakeComparable][LeafAreaIndex/AVH15C1][RTM_ens37_case_2] Spatial data was [INFO][0][MakeComparable][LeafAreaInde[DEBUG][0][WorkConfront][LeafAreaIndex/AVH15C1][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/[INFO][0][AnalysisMeanStateSpace][lai] Bias scored using Collier2018
[INFO][0][AnalysisMeanStateSpace][lai] RMSE scored using Collier2018
[INFO][0][confront][LeafAreaIndex/AVH15C1][RTM_ens37_case_2] Success
[INFO][0][MakeComparable][LeafAreaIndex/MODIS][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [ 72 360 720] after: [ 72 360 711]
[DEBUG][0][WorkConfront][LeafAreaIndex/MODIS][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mo[DEBUG][0][WorkConfront][LeafAreaIndex/MODIS][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435[INFO][0][MakeComparable][LeafAreaIndex/MODIS][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [ 72 360 720] after: [ 72 360 711]
[DEBUG][0][WorkConfront][LeafAreaIndex/MODIS][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mo[DEBUG][0][WorkConfront][LeafAreaIndex/MODIS][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435[INFO][0][MakeComparable][LeafAreaIndex/MODIS][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [ 72 360 720] after: [ 72 360 711]
[DEBUG][0][WorkConfront][LeafAreaIndex/MODIS][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/EcosystemandCarbonCycle/LeafAreaIndex/MODIS/MODIS_RTM_ens37_case_2.nc'

[DEBUG][0][WorkConfront][NetEcosystemExchange/FLUXNET2015][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Da[DEBUG][0][WorkConfront][NetEcosystemExchange/FLUXNET2015][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    w[DEBUG][0][WorkConfront][NetEcosystemExchange/FLUXNET2015][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Da[DEBUG][0][WorkConfront][NetEcosys[DEBUG][0][WorkConfront][NetEcosystemExchange/FLUXNET2015][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontatio[DEBUG][0][WorkConfront][NetEcosystemExchange/FLUXNET2015][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/EcosystemandCarbonCycle/NetEcosystemExchange/FLUXNET2015/FLUXNET2015_RTM_ens37_case_2.nc'

[DEBUG][0][WorkConfront][EcosystemRespiration/FLUXNET2015][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Da[DEBUG][0][WorkConfront][EcosystemRespiration/FLUXNET2015][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    w[DEBUG][0][WorkConfront][EcosystemRespiration/FLUXNET2015][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Da[DEBUG][0][WorkConfront][EcosystemRespiration/FLUXNET2015][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    w[DEBUG][0][WorkConfront][EcosystemRespiration/FLUXNET2015][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Da[DEBUG][0][WorkConfront][Ecosystem[DEBUG][0][WorkConfront][EcosystemRespiration/FLUXNET2015][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontatio[INFO][0][MakeComparable][EcosystemRespiration/FLUXCOM][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [408 360 720] after: [408 360 711]
[DEBUG][0][WorkConfront][EcosystemRespiration/FLUXCOM][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Datase[DEBUG][0][WorkConfront][EcosystemRespiration/FLUXCOM][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confro[INFO][0][MakeComparable][EcosystemRespiration/FLUXCOM][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [408 360 720] after: [408 360 711]
[DEBUG][0][WorkConfront][EcosystemRespiration/FLUXCOM][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Datase[DEBUG][0][WorkConfront][EcosystemRespiration/FLUXCOM][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confro[INFO][0][MakeComparable][EcosystemRespiration/FLUXCOM][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [408 360 720] after: [408 360 711]
[DEBUG][0][WorkConfront][EcosystemRespiration/FLUXCOM][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Datase[DEBUG][0][WorkConfront][EcosystemRespiration/FLUXCOM][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confro[INFO][0][MakeComparable][Evapotranspiration/GLEAMv3.3a][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [468 360 720] after: [468 360 711]
[DEBUG][0][WorkConfront][Evapotranspiration/GLEAMv3.3a][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-pack[INFO][0][Make[INFO][0][MakeComparable][Evapotranspiration/GLEAMv3.3a][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [468 360 720] after: [468 360 711]
[INFO][0][AnalysisMeanStateSpace][et] Bias scored using Collier2018
[INFO][0][AnalysisMeanStateSpace][et] RMSE scored using Collier2018
[INFO][0][confront][Evapotranspiration/GLEAMv3.3a][RTM_ens37_ca[INFO][0][Make[INFO][0][MakeComparable][Evapotranspiration/GLEAMv3.3a][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [468 360 720] after: [468 360 711]
[INFO][0][AnalysisMeanStateSpace][et] Bias scored using Collier2018
[INFO][0][AnalysisMeanStateSpace][et] RMSE scored using Collier2018
[INFO][0][confront][Evapotranspiration/GLEAMv3.3a][RTM_ens37_ca[INFO][0][Make[INFO][0][MakeComparable][Evapotranspiration/MODIS][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [168 360 720] after: [168 [INFO][0][INFO][0][AnalysisMeanStateSpace][et] Bias scored using Col[INFO][0][INFO][0][AnalysisMeanStateSpace][et] RMSE scored using Collier2018
[INFO][0][confront][Evapotranspiration/MODIS][RTM_ens37_case_0] Succ[INF[INFO][0][MakeComparable][Evapotranspiration/MODIS][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [168 360 720] after: [168 360 7[DEBUG][0][WorkConfront][Evapotranspiration/MODIS][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2750, in __enter__
    self.obs_dset = Dataset(self.obs_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/HydrologyCycle/Evapotranspiration/MODIS/MODIS_Benchmark.nc'

[INFO][0][MakeComparable][Evapotranspiration/MODIS][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [168 360 720] after: [168 360 711]
[DEBUG][0][[INFO][0][AnalysisMeanStateSpace][et] Bias scored using Collier2018
[INFO][0][AnalysisMeanStateSpace][et] RMSE scored using Collier2018
[INFO][0][confront][Evapotranspiration/MODIS][RTM_ens37_case_2] Success
[INFO][0][MakeComparable][Evapotranspiration/MOD16A2][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [180 360 720] after: [180 360 711]
[INFO][0][AnalysisMeanStateSpace][et] Bias scored using Collier2018
[INFO][0][AnalysisMeanStateSpace][et] RMSE scored using Collier2018
[INFO][0][confront][Evapotranspiration/MOD16A2][RTM_ens37_case_0] Success
[INFO][0][MakeComparable][Evapotranspiration/MOD16A2][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [180 360 720] after: [180 360 711]
[INFO][0][AnalysisMeanStateSpace][et] Bias scored using Collier2018
[INFO][0][AnalysisMeanStateSpace][et] RMSE scored using Collier2018
[INFO][0][confront][Evapotranspiration/MOD16A2][RTM_ens37_case_1] Success
[INFO][0][MakeComparable][Evapotranspiration/MOD16A2][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [180 360 720] after: [180 360 711]
[INFO][0][AnalysisMeanStateSpace][et] Bias scored using Collier2018
[INFO][0][AnalysisMeanStateSpace][et] RMSE scored using Collier2018
[INFO][0][confront][Evapotranspiration/MOD16A2][RTM_ens37_case_2] Success
[INFO][0][MakeComparable][LatentHeat/FLUXCOM][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [420 360 720] after: [420 360 711]
[DEBUG][0][WorkConfront][LatentHeat/FLUXCOM][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/HydrologyCycle/LatentHeat/FLUXCOM/FLUXCOM_RTM_ens37_case_0.nc'

[INFO][0][MakeComparable][LatentHeat/FLUXCOM][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [420 360 720] after: [420 360 711]
[DEBUG][0][WorkConfront][LatentHeat/FLUXCOM][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/HydrologyCycle/LatentHeat/FLUXCOM/FLUXCOM_RTM_ens37_case_1.nc'

[INFO][0][MakeComparable][LatentHeat/FLUXCOM][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [420 360 720] after: [420 360 711]
[DEBUG][0][WorkConfront][LatentHeat/FLUXCOM][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/HydrologyCycle/LatentHeat/FLUXCOM/FLUXCOM_RTM_ens37_case_2.nc'

[INFO][0][MakeComparable][LatentHeat/DOLCE][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [120 360 720] after: [120 360 711]
[DEBUG][0][WorkConfront][LatentHeat/DOLCE][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/HydrologyCycle/LatentHeat/DOLCE/DOLCE_RTM_ens37_case_0.nc'

[INFO][0][MakeComparable][LatentHeat/DOLCE][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [120 360 720] after: [120 360 711]
[DEBUG][0][WorkConfront][LatentHeat/DOLCE][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/HydrologyCycle/LatentHeat/DOLCE/DOLCE_RTM_ens37_case_1.nc'

[INFO][0][MakeComparable][LatentHeat/DOLCE][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [120 360 720] after: [120 360 711]
[DEBUG][0][WorkConfront][LatentHeat/DOLCE][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/HydrologyCycle/LatentHeat/DOLCE/DOLCE_RTM_ens37_case_2.nc'

[INFO][0][MakeComparable][LatentHeat/CLASS][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [ 84 360 720] after: [ 84 360 711]
[DEBUG][0][WorkConfront][LatentHeat/CLASS][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/HydrologyCycle/LatentHeat/CLASS/CLASS_RTM_ens37_case_0.nc'

[INFO][0][MakeComparable][LatentHeat/CLASS][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [ 84 360 720] after: [ 84 360 711]
[DEBUG][0][WorkConfront][LatentHeat/CLASS][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/HydrologyCycle/LatentHeat/CLASS/CLASS_RTM_ens37_case_1.nc'

[INFO][0][MakeComparable][LatentHeat/CLASS][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [ 84 360 720] after: [ 84 360 711]
[DEBUG][0][WorkConfront][LatentHeat/CLASS][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/HydrologyCycle/LatentHeat/CLASS/CLASS_RTM_ens37_case_2.nc'

[INFO][0][MakeComparable][LatentHeat/WECANN][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [108 180 360] after: [108 180 356]
[DEBUG][0][WorkConfront][LatentHeat/WECANN][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/HydrologyCycle/LatentHeat/WECANN/WECANN_RTM_ens37_case_0.nc'

[INFO][0][MakeComparable][LatentHeat/WECANN][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [108 180 360] after: [108 180 356]
[DEBUG][0][WorkConfront][LatentHeat/WECANN][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/HydrologyCycle/LatentHeat/WECANN/WECANN_RTM_ens37_case_1.nc'

[INFO][0][MakeComparable][LatentHeat/WECANN][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [108 180 360] after: [108 180 356]
[DEBUG][0][WorkConfront][LatentHeat/WECANN][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/HydrologyCycle/LatentHeat/WECANN/WECANN_RTM_ens37_case_2.nc'

[DEBUG][0][WorkConfront][SensibleHeat/FLUXNET2015][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/HydrologyCycle/SensibleHeat/FLUXNET2015/FLUXNET2015_RTM_ens37_case_0.nc'

[DEBUG][0][WorkConfront][SensibleHeat/FLUXNET2015][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/HydrologyCycle/SensibleHeat/FLUXNET2015/FLUXNET2015_RTM_ens37_case_1.nc'

[DEBUG][0][WorkConfront][SensibleHeat/FLUXNET2015][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/HydrologyCycle/SensibleHeat/FLUXNET2015/FLUXNET2015_RTM_ens37_case_2.nc'

[INFO][0][MakeComparable][SensibleHeat/FLUXCOM][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [420 360 720] after: [420 360 711]
[DEBUG][0][WorkConfront][SensibleHeat/FLUXCOM][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/HydrologyCycle/SensibleHeat/FLUXCOM/FLUXCOM_RTM_ens37_case_0.nc'

[INFO][0][MakeComparable][SensibleHeat/FLUXCOM][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [420 360 720] after: [420 360 711]
[DEBUG][0][WorkConfront][SensibleHeat/FLUXCOM][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/HydrologyCycle/SensibleHeat/FLUXCOM/FLUXCOM_RTM_ens37_case_1.nc'

[INFO][0][MakeComparable][SensibleHeat/FLUXCOM][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [420 360 720] after: [420 360 711]
[DEBUG][0][WorkConfront][SensibleHeat/FLUXCOM][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/HydrologyCycle/SensibleHeat/FLUXCOM/FLUXCOM_RTM_ens37_case_2.nc'

[INFO][0][MakeComparable][SensibleHeat/CLASS][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [ 84 360 720] after: [ 84 360 711]
[DEBUG][0][WorkConfront][SensibleHeat/CLASS][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/HydrologyCycle/SensibleHeat/CLASS/CLASS_RTM_ens37_case_0.nc'

[INFO][0][MakeComparable][SensibleHeat/CLASS][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [ 84 360 720] after: [ 84 360 711]
[DEBUG][0][WorkConfront][SensibleHeat/CLASS][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/HydrologyCycle/SensibleHeat/CLASS/CLASS_RTM_ens37_case_1.nc'

[INFO][0][MakeComparable][SensibleHeat/CLASS][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [ 84 360 720] after: [ 84 360 711]
[DEBUG][0][WorkConfront][SensibleHeat/CLASS][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/HydrologyCycle/SensibleHeat/CLASS/CLASS_RTM_ens37_case_2.nc'

[INFO][0][MakeComparable][SensibleHeat/WECANN][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [108 180 360] after: [108 180 356]
[DEBUG][0][WorkConfront][SensibleHeat/WECANN][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/HydrologyCycle/SensibleHeat/WECANN/WECANN_RTM_ens37_case_0.nc'

[INFO][0][MakeComparable][SensibleHeat/WECANN][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [108 180 360] after: [108 180 356]
[DEBUG][0][WorkConfront][SensibleHeat/WECANN][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/HydrologyCycle/SensibleHeat/WECANN/WECANN_RTM_ens37_case_1.nc'

[INFO][0][MakeComparable][SensibleHeat/WECANN][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [108 180 360] after: [108 180 356]
[DEBUG][0][WorkConfront][SensibleHeat/WECANN][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/HydrologyCycle/SensibleHeat/WECANN/WECANN_RTM_ens37_case_2.nc'

[DEBUG][0][WorkConfront][Albedo/CERES][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 161, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/Albedo/CERES/CERES_RTM_ens37_case_0.nc'

[DEBUG][0][WorkConfront][Albedo/CERES][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 161, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/Albedo/CERES/CERES_RTM_ens37_case_1.nc'

[DEBUG][0][WorkConfront][Albedo/CERES][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 161, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/Albedo/CERES/CERES_RTM_ens37_case_2.nc'

[DEBUG][0][WorkConfront][Albedo/GEWEX.SRB][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 161, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/Albedo/GEWEX.SRB/GEWEX.SRB_RTM_ens37_case_0.nc'

[DEBUG][0][WorkConfront][Albedo/GEWEX.SRB][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 161, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/Albedo/GEWEX.SRB/GEWEX.SRB_RTM_ens37_case_1.nc'

[DEBUG][0][WorkConfront][Albedo/GEWEX.SRB][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ConfAlbedo.py", line 161, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/Albedo/GEWEX.SRB/GEWEX.SRB_RTM_ens37_case_2.nc'

[INFO][0][MakeComparable][SurfaceUpwardSWRadiation/CERESed4.1][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [228 360 720] after: [228 360 711]
[INFO][0][AnalysisMeanStateSpace][rsus] Bias scored using Collier2018
[INFO][0][AnalysisMeanStateSpace][rsus] RMSE scored using Collier2018
[INFO][0][confront][SurfaceUpwardSWRadiation/CERESed4.1][RTM_ens37_case_0] Success
[INFO][0][MakeComparable][SurfaceUpwardSWRadiation/CERESed4.1][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [228 360 720] after: [228 360 711]
[DEBUG][0][WorkConfront][SurfaceUpwardSWRadiation/CERESed4.1][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceUpwardSWRadiation/CERESed4.1/CERESed4.1_RTM_ens37_case_1.nc'

[INFO][0][MakeComparable][SurfaceUpwardSWRadiation/CERESed4.1][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [228 360 720] after: [228 360 711]
[INFO][0][AnalysisMeanStateSpace][rsus] Bias scored using Collier2018
[INFO][0][AnalysisMeanStateSpace][rsus] RMSE scored using Collier2018
[INFO][0][confront][SurfaceUpwardSWRadiation/CERESed4.1][RTM_ens37_case_2] Success
[INFO][0][AnalysisMeanStateSites][rsus] Bias scored using Collier2018
[INFO][0][AnalysisMeanStateSites][rsus] RMSE scored using Collier2018
[INFO][0][confront][SurfaceUpwardSWRadiation/FLUXNET2015][RTM_ens37_case_0] Success
[DEBUG][0][WorkConfront][SurfaceUpwardSWRadiation/FLUXNET2015][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceUpwardSWRadiation/FLUXNET2015/FLUXNET2015_RTM_ens37_case_1.nc'

[DEBUG][0][WorkConfront][SurfaceUpwardSWRadiation/FLUXNET2015][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceUpwardSWRadiation/FLUXNET2015/FLUXNET2015_RTM_ens37_case_2.nc'

[INFO][0][MakeComparable][SurfaceUpwardSWRadiation/GEWEX.SRB][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [288 360 720] after: [288 360 711]
[DEBUG][0][WorkConfront][SurfaceUpwardSWRadiation/GEWEX.SRB][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceUpwardSWRadiation/GEWEX.SRB/GEWEX.SRB_RTM_ens37_case_0.nc'

[INFO][0][MakeComparable][SurfaceUpwardSWRadiation/GEWEX.SRB][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [288 360 720] after: [288 360 711]
[DEBUG][0][WorkConfront][SurfaceUpwardSWRadiation/GEWEX.SRB][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceUpwardSWRadiation/GEWEX.SRB/GEWEX.SRB_RTM_ens37_case_1.nc'

[INFO][0][MakeComparable][SurfaceUpwardSWRadiation/GEWEX.SRB][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [288 360 720] after: [288 360 711]
[DEBUG][0][WorkConfront][SurfaceUpwardSWRadiation/GEWEX.SRB][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceUpwardSWRadiation/GEWEX.SRB/GEWEX.SRB_RTM_ens37_case_2.nc'

[DEBUG][0][WorkConfront][SurfaceUpwardSWRadiation/WRMC.BSRN][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceUpwardSWRadiation/WRMC.BSRN/WRMC.BSRN_RTM_ens37_case_0.nc'

[DEBUG][0][WorkConfront][SurfaceUpwardSWRadiation/WRMC.BSRN][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceUpwardSWRadiation/WRMC.BSRN/WRMC.BSRN_RTM_ens37_case_1.nc'

[DEBUG][0][WorkConfront][SurfaceUpwardSWRadiation/WRMC.BSRN][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceUpwardSWRadiation/WRMC.BSRN/WRMC.BSRN_RTM_ens37_case_2.nc'

[INFO][0][MakeComparable][SurfaceNetSWRadiation/CERESed4.1][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [228 360 720] after: [228 360 711]
[DEBUG][0][WorkConfront][SurfaceNetSWRadiation/CERESed4.1][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetSWRadiation/CERESed4.1/CERESed4.1_RTM_ens37_case_0.nc'

[INFO][0][MakeComparable][SurfaceNetSWRadiation/CERESed4.1][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [228 360 720] after: [228 360 711]
[DEBUG][0][WorkConfront][SurfaceNetSWRadiation/CERESed4.1][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetSWRadiation/CERESed4.1/CERESed4.1_RTM_ens37_case_1.nc'

[INFO][0][MakeComparable][SurfaceNetSWRadiation/CERESed4.1][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [228 360 720] after: [228 360 711]
[DEBUG][0][WorkConfront][SurfaceNetSWRadiation/CERESed4.1][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetSWRadiation/CERESed4.1/CERESed4.1_RTM_ens37_case_2.nc'

[DEBUG][0][WorkConfront][SurfaceNetSWRadiation/FLUXNET2015][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetSWRadiation/FLUXNET2015/FLUXNET2015_RTM_ens37_case_0.nc'

[DEBUG][0][WorkConfront][SurfaceNetSWRadiation/FLUXNET2015][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetSWRadiation/FLUXNET2015/FLUXNET2015_RTM_ens37_case_1.nc'

[DEBUG][0][WorkConfront][SurfaceNetSWRadiation/FLUXNET2015][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetSWRadiation/FLUXNET2015/FLUXNET2015_RTM_ens37_case_2.nc'

[INFO][0][MakeComparable][SurfaceNetSWRadiation/GEWEX.SRB][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [288 360 720] after: [288 360 711]
[DEBUG][0][WorkConfront][SurfaceNetSWRadiation/GEWEX.SRB][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetSWRadiation/GEWEX.SRB/GEWEX.SRB_RTM_ens37_case_0.nc'

[INFO][0][MakeComparable][SurfaceNetSWRadiation/GEWEX.SRB][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [288 360 720] after: [288 360 711]
[DEBUG][0][WorkConfront][SurfaceNetSWRadiation/GEWEX.SRB][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetSWRadiation/GEWEX.SRB/GEWEX.SRB_RTM_ens37_case_1.nc'

[INFO][0][MakeComparable][SurfaceNetSWRadiation/GEWEX.SRB][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [288 360 720] after: [288 360 711]
[DEBUG][0][WorkConfront][SurfaceNetSWRadiation/GEWEX.SRB][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetSWRadiation/GEWEX.SRB/GEWEX.SRB_RTM_ens37_case_2.nc'

[DEBUG][0][WorkConfront][SurfaceNetSWRadiation/WRMC.BSRN][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetSWRadiation/WRMC.BSRN/WRMC.BSRN_RTM_ens37_case_0.nc'

[DEBUG][0][WorkConfront][SurfaceNetSWRadiation/WRMC.BSRN][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetSWRadiation/WRMC.BSRN/WRMC.BSRN_RTM_ens37_case_1.nc'

[DEBUG][0][WorkConfront][SurfaceNetSWRadiation/WRMC.BSRN][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetSWRadiation/WRMC.BSRN/WRMC.BSRN_RTM_ens37_case_2.nc'

[INFO][0][MakeComparable][SurfaceUpwardLWRadiation/CERESed4.1][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [228 360 720] after: [228 360 711]
[DEBUG][0][WorkConfront][SurfaceUpwardLWRadiation/CERESed4.1][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceUpwardLWRadiation/CERESed4.1/CERESed4.1_RTM_ens37_case_0.nc'

[INFO][0][MakeComparable][SurfaceUpwardLWRadiation/CERESed4.1][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [228 360 720] after: [228 360 711]
[DEBUG][0][WorkConfront][SurfaceUpwardLWRadiation/CERESed4.1][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceUpwardLWRadiation/CERESed4.1/CERESed4.1_RTM_ens37_case_1.nc'

[INFO][0][MakeComparable][SurfaceUpwardLWRadiation/CERESed4.1][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [228 360 720] after: [228 360 711]
[DEBUG][0][WorkConfront][SurfaceUpwardLWRadiation/CERESed4.1][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceUpwardLWRadiation/CERESed4.1/CERESed4.1_RTM_ens37_case_2.nc'

[DEBUG][0][WorkConfront][SurfaceUpwardLWRadiation/FLUXNET2015][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceUpwardLWRadiation/FLUXNET2015/FLUXNET2015_RTM_ens37_case_0.nc'

[DEBUG][0][WorkConfront][SurfaceUpwardLWRadiation/FLUXNET2015][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceUpwardLWRadiation/FLUXNET2015/FLUXNET2015_RTM_ens37_case_1.nc'

[DEBUG][0][WorkConfront][SurfaceUpwardLWRadiation/FLUXNET2015][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceUpwardLWRadiation/FLUXNET2015/FLUXNET2015_RTM_ens37_case_2.nc'

[INFO][0][MakeComparable][SurfaceUpwardLWRadiation/GEWEX.SRB][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [288 360 720] after: [288 360 711]
[DEBUG][0][WorkConfront][SurfaceUpwardLWRadiation/GEWEX.SRB][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceUpwardLWRadiation/GEWEX.SRB/GEWEX.SRB_RTM_ens37_case_0.nc'

[INFO][0][MakeComparable][SurfaceUpwardLWRadiation/GEWEX.SRB][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [288 360 720] after: [288 360 711]
[DEBUG][0][WorkConfront][SurfaceUpwardLWRadiation/GEWEX.SRB][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceUpwardLWRadiation/GEWEX.SRB/GEWEX.SRB_RTM_ens37_case_1.nc'

[INFO][0][MakeComparable][SurfaceUpwardLWRadiation/GEWEX.SRB][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [288 360 720] after: [288 360 711]
[DEBUG][0][WorkConfront][SurfaceUpwardLWRadiation/GEWEX.SRB][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceUpwardLWRadiation/GEWEX.SRB/GEWEX.SRB_RTM_ens37_case_2.nc'

[DEBUG][0][WorkConfront][SurfaceUpwardLWRadiation/WRMC.BSRN][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceUpwardLWRadiation/WRMC.BSRN/WRMC.BSRN_RTM_ens37_case_0.nc'

[DEBUG][0][WorkConfront][SurfaceUpwardLWRadiation/WRMC.BSRN][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceUpwardLWRadiation/WRMC.BSRN/WRMC.BSRN_RTM_ens37_case_1.nc'

[DEBUG][0][WorkConfront][SurfaceUpwardLWRadiation/WRMC.BSRN][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceUpwardLWRadiation/WRMC.BSRN/WRMC.BSRN_RTM_ens37_case_2.nc'

[INFO][0][MakeComparable][SurfaceNetLWRadiation/CERESed4.1][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [228 360 720] after: [228 360 711]
[DEBUG][0][WorkConfront][SurfaceNetLWRadiation/CERESed4.1][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetLWRadiation/CERESed4.1/CERESed4.1_RTM_ens37_case_0.nc'

[INFO][0][MakeComparable][SurfaceNetLWRadiation/CERESed4.1][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [228 360 720] after: [228 360 711]
[DEBUG][0][WorkConfront][SurfaceNetLWRadiation/CERESed4.1][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetLWRadiation/CERESed4.1/CERESed4.1_RTM_ens37_case_1.nc'

[INFO][0][MakeComparable][SurfaceNetLWRadiation/CERESed4.1][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [228 360 720] after: [228 360 711]
[DEBUG][0][WorkConfront][SurfaceNetLWRadiation/CERESed4.1][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetLWRadiation/CERESed4.1/CERESed4.1_RTM_ens37_case_2.nc'

[DEBUG][0][WorkConfront][SurfaceNetLWRadiation/FLUXNET2015][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetLWRadiation/FLUXNET2015/FLUXNET2015_RTM_ens37_case_0.nc'

[INFO][0][AnalysisMeanStateSites][rlns] Bias scored using Collier2018
[INFO][0][AnalysisMeanStateSites][rlns] RMSE scored using Collier2018
[INFO][0][confront][SurfaceNetLWRadiation/FLUXNET2015][RTM_ens37_case_1] Success
[DEBUG][0][WorkConfront][SurfaceNetLWRadiation/FLUXNET2015][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetLWRadiation/FLUXNET2015/FLUXNET2015_RTM_ens37_case_2.nc'

[INFO][0][MakeComparable][SurfaceNetLWRadiation/GEWEX.SRB][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [288 360 720] after: [288 360 711]
[DEBUG][0][WorkConfront][SurfaceNetLWRadiation/GEWEX.SRB][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetLWRadiation/GEWEX.SRB/GEWEX.SRB_RTM_ens37_case_0.nc'

[INFO][0][MakeComparable][SurfaceNetLWRadiation/GEWEX.SRB][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [288 360 720] after: [288 360 711]
[DEBUG][0][WorkConfront][SurfaceNetLWRadiation/GEWEX.SRB][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetLWRadiation/GEWEX.SRB/GEWEX.SRB_RTM_ens37_case_1.nc'

[INFO][0][MakeComparable][SurfaceNetLWRadiation/GEWEX.SRB][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [288 360 720] after: [288 360 711]
[DEBUG][0][WorkConfront][SurfaceNetLWRadiation/GEWEX.SRB][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetLWRadiation/GEWEX.SRB/GEWEX.SRB_RTM_ens37_case_2.nc'

[DEBUG][0][WorkConfront][SurfaceNetLWRadiation/WRMC.BSRN][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetLWRadiation/WRMC.BSRN/WRMC.BSRN_RTM_ens37_case_0.nc'

[DEBUG][0][WorkConfront][SurfaceNetLWRadiation/WRMC.BSRN][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetLWRadiation/WRMC.BSRN/WRMC.BSRN_RTM_ens37_case_1.nc'

[DEBUG][0][WorkConfront][SurfaceNetLWRadiation/WRMC.BSRN][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetLWRadiation/WRMC.BSRN/WRMC.BSRN_RTM_ens37_case_2.nc'

[INFO][0][MakeComparable][SurfaceNetRadiation/CERESed4.1][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [228 360 720] after: [228 360 711]
[DEBUG][0][WorkConfront][SurfaceNetRadiation/CERESed4.1][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetRadiation/CERESed4.1/CERESed4.1_RTM_ens37_case_0.nc'

[INFO][0][MakeComparable][SurfaceNetRadiation/CERESed4.1][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [228 360 720] after: [228 360 711]
[INFO][0][AnalysisMeanStateSpace][rns] Bias scored using Collier2018
[INFO][0][AnalysisMeanStateSpace][rns] RMSE scored using Collier2018
[INFO][0][confront][SurfaceNetRadiation/CERESed4.1][RTM_ens37_case_1] Success
[INFO][0][MakeComparable][SurfaceNetRadiation/CERESed4.1][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [228 360 720] after: [228 360 711]
[DEBUG][0][WorkConfront][SurfaceNetRadiation/CERESed4.1][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetRadiation/CERESed4.1/CERESed4.1_RTM_ens37_case_2.nc'

[DEBUG][0][WorkConfront][SurfaceNetRadiation/FLUXNET2015][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetRadiation/FLUXNET2015/FLUXNET2015_RTM_ens37_case_0.nc'

[DEBUG][0][WorkConfront][SurfaceNetRadiation/FLUXNET2015][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetRadiation/FLUXNET2015/FLUXNET2015_RTM_ens37_case_1.nc'

[DEBUG][0][WorkConfront][SurfaceNetRadiation/FLUXNET2015][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetRadiation/FLUXNET2015/FLUXNET2015_RTM_ens37_case_2.nc'

[INFO][0][MakeComparable][SurfaceNetRadiation/GEWEX.SRB][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [288 360 720] after: [288 360 711]
[DEBUG][0][WorkConfront][SurfaceNetRadiation/GEWEX.SRB][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetRadiation/GEWEX.SRB/GEWEX.SRB_RTM_ens37_case_0.nc'

[INFO][0][MakeComparable][SurfaceNetRadiation/GEWEX.SRB][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [288 360 720] after: [288 360 711]
[DEBUG][0][WorkConfront][SurfaceNetRadiation/GEWEX.SRB][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetRadiation/GEWEX.SRB/GEWEX.SRB_RTM_ens37_case_1.nc'

[INFO][0][MakeComparable][SurfaceNetRadiation/GEWEX.SRB][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [288 360 720] after: [288 360 711]
[DEBUG][0][WorkConfront][SurfaceNetRadiation/GEWEX.SRB][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetRadiation/GEWEX.SRB/GEWEX.SRB_RTM_ens37_case_2.nc'

[DEBUG][0][WorkConfront][SurfaceNetRadiation/WRMC.BSRN][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetRadiation/WRMC.BSRN/WRMC.BSRN_RTM_ens37_case_0.nc'

[DEBUG][0][WorkConfront][SurfaceNetRadiation/WRMC.BSRN][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetRadiation/WRMC.BSRN/WRMC.BSRN_RTM_ens37_case_1.nc'

[DEBUG][0][WorkConfront][SurfaceNetRadiation/WRMC.BSRN][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetRadiation/WRMC.BSRN/WRMC.BSRN_RTM_ens37_case_2.nc'

[INFO][0][MakeComparable][SurfaceNetRadiation/CLASS][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [ 84 360 720] after: [ 84 360 711]
[DEBUG][0][WorkConfront][SurfaceNetRadiation/CLASS][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetRadiation/CLASS/CLASS_RTM_ens37_case_0.nc'

[INFO][0][MakeComparable][SurfaceNetRadiation/CLASS][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [ 84 360 720] after: [ 84 360 711]
[DEBUG][0][WorkConfront][SurfaceNetRadiation/CLASS][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetRadiation/CLASS/CLASS_RTM_ens37_case_1.nc'

[INFO][0][MakeComparable][SurfaceNetRadiation/CLASS][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [ 84 360 720] after: [ 84 360 711]
[DEBUG][0][WorkConfront][SurfaceNetRadiation/CLASS][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetRadiation/CLASS/CLASS_RTM_ens37_case_2.nc'

[INFO][0][MakeComparable][GroundHeatFlux/CLASS][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [ 84 360 720] after: [ 84 360 711]
[DEBUG][0][WorkConfront][GroundHeatFlux/CLASS][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/GroundHeatFlux/CLASS/CLASS_RTM_ens37_case_0.nc'

[INFO][0][MakeComparable][GroundHeatFlux/CLASS][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [ 84 360 720] after: [ 84 360 711]
[DEBUG][0][WorkConfront][GroundHeatFlux/CLASS][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/GroundHeatFlux/CLASS/CLASS_RTM_ens37_case_1.nc'

[INFO][0][MakeComparable][GroundHeatFlux/CLASS][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [ 84 360 720] after: [ 84 360 711]
[DEBUG][0][WorkConfront][GroundHeatFlux/CLASS][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/GroundHeatFlux/CLASS/CLASS_RTM_ens37_case_2.nc'

SurfaceNetRadiation/CLASS/CLASS_RTM_ens37_case_2.nc'

[INFO][0][MakeComparable][GroundHeatFlux/CLASS][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [ 84 360 720] after: [ 84 360 711]
[DEBUG][0][WorkConfront][GroundHeatFlux/CLASS][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/GroundHeatFlux/CLASS/CLASS_RTM_ens37_case_0.nc'

[INFO][0][MakeComparable][GroundHeatFlux/CLASS][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [ 84 360 720] after: [ 84 360 711]
[DEBUG][0][WorkConfront][GroundHeatFlux/CLASS][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/GroundHeatFlux/CLASS/CLASS_RTM_ens37_case_1.nc'

[INFO][0][MakeComparable][GroundHeatFlux/CLASS][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [ 84 360 720] after: [ 84 360 711]
[DEBUG][0][WorkConfront][GroundHeatFlux/CLASS][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/GroundHeatFlux/CLASS/CLASS_RTM_ens37_case_2.nc'

tCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/SurfaceNetRadiation/CLASS/CLASS_RTM_ens37_case_2.nc'

[I[INFO][0][MakeComparable][GroundHeatFlux/CLASS][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [ 84 360 720] after: [ 84 360 711[D[DEBUG][0][WorkConfront][GroundHeatFlux/CLASS][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/GroundHeatFlux/CLASS/CLASS_RTM_ens37_case_0.nc'[INFO][0][MakeComparable][GroundHeatFlux/CLASS][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [ 84 360 720] after: [ 84 360 711]
[D[DEBUG][0][WorkConfront][GroundHeatFlux/CLASS][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/GroundHeatFlux/CLASS/CLASS_RTM_ens37_case_1.nc'[INFO][0][MakeComparable][GroundHeatFlux/CLASS][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [ 84 360 720] after: [ 84 360 711]
[DEBUG][0][WorkConfront][GroundHeatFlux/CLASS][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/GroundHeatFlux/CLASS/CLASS_RTM_ens37_case_2.nc'



adiation/CLASS][RTM_ens37_case_2]
Traceback (most recent call last)[DEBUG][0][WorkConfront][SurfaceNetRadiation/CLASS][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, i[INFO][0][MakeComparable][GroundHeatFlux/CLASS][RTM_ens37_case_0] Spatial data was clipped from the reference:  before: [ 84 360 720] after: [ 84 360 711]
[DEBUG][0][WorkConfront][GroundHeatFlux/CLASS][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/[DEBUG][0][WorkConfront][GroundHeatFlux/CL[DEBUG][0][WorkConfront][GroundHeatFlux/CLASS][RTM_ens37_case_0]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/r[INFO][0][MakeComparable][GroundHeatFlux/CLASS][RTM_ens37_case_1] Spatial data was clipped from the reference:  before: [ 84 360 720] after: [ 84 360 711]
[DEBUG][0][WorkConfront][GroundHeatFlux/CLASS][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/[DEBUG][0][WorkConfront][GroundHeatFlux/CLASS][RTM_ens37_case_1]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/[INFO][0][MakeComparable][GroundHeatFlux/CLASS][RTM_ens37_case_2] Spatial data was clipped from the reference:  before: [ 84 360 720] after: [ 84 360 711]
[DEBUG][0][WorkConfront][GroundHeatFlux/CLASS][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/[DEBUG][0][WorkConfront][GroundHeatFlux/CLASS][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._[DEBUG][0][WorkConfront][GroundHeatFlux/CLASS][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/GroundHeatFlux/CLASS/CLASS_RTM_ens37_case_2.nc'

Flux/CLASS/CLASS_RTM_ens37_case_2.nc'

ocal/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensur[DEBUG][0][WorkConfront][GroundHeatFlux/CLASS][RTM_ens37_case_2]
Traceback (most recent call last):
  File "/var/run/palsd/fcb0f8c0-2212-4e9c-a8c5-a1674d87372b/files/ilamb-run", line 561, in WorkConfront
    c.confront(m)
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/Confrontation.py", line 435, in confront
    with il.FileContextManager(self.master, mod_file, obs_file) as fcm:
  File "/glade/u/home/rfisher/.local/lib/python3.9/site-packages/ILAMB/ilamblib.py", line 2748, in __enter__
    self.mod_dset = Dataset(self.mod_results, mode="w")
  File "src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 2026, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'./_build/RadiationandEnergyCycle/GroundHeatFlux/CLASS/CLASS_RTM_ens37_case_2.nc'

